name: cinemafan
description: Movies & Series Encyclopedia, for cinema fans and series addicts.
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  card_swiper: ^3.0.1
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.3
  flutter_riverpod: ^2.3.6
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.6.0
  go_router: ^10.0.0
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icon/CinemaFan-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#9E6BF8"
  color_dark: "#9E6BF8"
  android_12:
    color: "#9E6BF8"
    color_dark: "#9E6BF8"
